name       : smartmontools
version    : '7.0'
release    : 3
source     :
    - https://netcologne.dl.sourceforge.net/project/smartmontools/smartmontools/7.0/smartmontools-7.0.tar.gz : e5e1ac2786bc87fdbd6f92d0ee751b799fbb3e1a09c0a6a379f9eb64b3e8f61c
license    : GPL-2.0
component  : system.utils
summary    : smartmontools to check S.M.A.R.T information on harddrives/SSD
description: |
    The smartmontools package contains two utility programs (smartctl and smartd) to control and monitor storage systems using the Self-Monitoring, Analysis and Reporting Technology System (SMART) built into most modern ATA/SATA, SCSI/SAS and NVMe disks
builddeps  :
    - pkgconfig(libcap-ng)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
