name       : smartmontools
version    : 6.6
release    : 2
source     :
    - https://netcologne.dl.sourceforge.net/project/smartmontools/smartmontools/6.6/smartmontools-6.6.tar.gz : 51f43d0fb064fccaf823bbe68cf0d317d0895ff895aa353b3339a3b316a53054
license    : GPL-2.0
component  : system.utils
summary    : smartmontools to check S.M.A.R.T information on harddrives/SSD
description: |
    The smartmontools package contains two utility programs (smartctl and smartd) to control and monitor storage systems using the Self-Monitoring, Analysis and Reporting Technology System (SMART) built into most modern ATA/SATA, SCSI/SAS and NVMe disks
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
