name       : smartmontools
version    : '7.1'
release    : 4
source     :
    - https://netcologne.dl.sourceforge.net/project/smartmontools/smartmontools/7.1/smartmontools-7.1.tar.gz : 3f734d2c99deb1e4af62b25d944c6252de70ca64d766c4c7294545a2e659b846
license    : GPL-2.0-or-later
component  : system.utils
summary    : Check S.M.A.R.T information on hard and solid-state disks
description: |
    The smartmontools package contains two utility programs (smartctl and smartd) to control and monitor storage systems using the Self-Monitoring, Analysis and Reporting Technology System (SMART) built into most modern ATA/SATA, SCSI/SAS and NVMe disks.
builddeps  :
    - pkgconfig(libcap-ng)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/smartd_warning.sh $installdir/usr/share/smartmontools
    rm -rf $installdir/etc
    find $installdir/usr/share/doc/smartmontools \
        -maxdepth 1 \
        -type f -not -name smartd.conf -delete

    install -dm00755 $installdir/usr/include
    mv $installdir/usr/share/smartmontools/*.h $installdir/usr/include
check      : |
    %make check
